//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP523Zemdikhanova_PiTPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketID { get; set; }
        public int UserID { get; set; }
        public int SessionID { get; set; }
        public int SitID { get; set; }
    
        public virtual Seat Seat { get; set; }
        public virtual Session Session { get; set; }
        public virtual User User { get; set; }
    }
}
